version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=me_au_database
      - DB_USER=postgres
      - SECRET_KEY=segredu
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=me_au_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d me_au_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
